### ISSUE TITLE
Brainstorm Possible Tests/Test Generators

### ISSUE THREAD

**Issue by alessiogambi** [TrackerSB/IEEEAITestChallenge2021#18]
List here some ideas for generating "interesting/diverse" tests for the competition

**Comment by alessiogambi** [comment]
Control traffic lights and test ego car at the intersection:
- find traffic lights on the map (either automatically or because we hardcode them) - see the example on controllable
- place the ego 20 meters before the traffic light
- tell the ego to drive through the intersection
- control the traffic lights to create the scenarios (green, turns, red)

We can also place the ego car in the middle of the intersection and play around with the traffic lights. We'll the car be able to move away the intersection if the traffic lights are red?

**Comment by alessiogambi** [comment]
Parking Lot Madness:
- If there's is a parking lot we can test the car to see if it can go out the parking lot or we can test the "smart summon" feature like tesla
- place the car in a parking lot
- place other cars in other parking lots
- place and move pedestrians (at random)
- move the other cars in the parking lot
- instruct the ego car to reach a pedestrian or the exit

**Comment by TriHuynh00** [comment]
Merge Lane Test Cases:
![Mergelane](https://user-images.githubusercontent.com/7724181/114263432-b3522e00-99e5-11eb-8108-d9a4c6ff3bfb.png)

**Comment by TriHuynh00** [comment]
Encroaching Vehicle:

![grafik](https://user-images.githubusercontent.com/7724181/115951990-02b75480-a4e4-11eb-8fc5-e69dc11dc65b.png)
